System.out.println("Enter a positive integer to create a MyInteger object or to move on to next part of program:MyInteger obj0 = new MyInteger(1);")
%nobj0.getValue() = 1
%nobj0.isEven() = false
%nobj0.isOdd() = true
%nobj0.isPrime() = false
%nEnter a positive integer to create a MyInteger object or to move on to next part of program:MyInteger obj0 = new MyInteger(2);
%nobj0.getValue() = 2
%nobj0.isEven() = true
%nobj0.isOdd() = false
%nobj0.isPrime() = true
%nEnter a positive integer to create a MyInteger object or to move on to next part of program:MyInteger obj0 = new MyInteger(3);
%nobj0.getValue() = 3
%nobj0.isEven() = false
%nobj0.isOdd() = true
%nobj0.isPrime() = true
%nEnter a positive integer to create a MyInteger object or to move on to next part of program:MyInteger obj0 = new MyInteger(7);
%nobj0.getValue() = 7
%nobj0.isEven() = false
%nobj0.isOdd() = true
%nobj0.isPrime() = true
%nEnter a positive integer to create a MyInteger object or to move on to next part of program:MyInteger obj0 = new MyInteger(8);
%nobj0.getValue() = 8
%nobj0.isEven() = true
%nobj0.isOdd() = false
%nobj0.isPrime() = false
%nEnter a positive integer to create a MyInteger object or to move on to next part of program:Enter a positive integer to test static isXXX(int) methods or to move on to next part of program:MyInteger.isEven(1) = false
%nMyInteger.isOdd(1) = true
%nMyInteger.isPrime(1) = false
%nEnter a positive integer to test static isXXX(int) methods or to move on to next part of program:MyInteger.isEven(2) = true
%nMyInteger.isOdd(2) = false
%nMyInteger.isPrime(2) = true
%nEnter a positive integer to test static isXXX(int) methods or to move on to next part of program:MyInteger.isEven(19) = false
%nMyInteger.isOdd(19) = true
%nMyInteger.isPrime(19) = true
%nEnter a positive integer to test static isXXX(int) methods or to move on to next part of program:MyInteger.isEven(23) = false
%nMyInteger.isOdd(23) = true
%nMyInteger.isPrime(23) = true
%nEnter a positive integer to test static isXXX(int) methods or to move on to next part of program:MyInteger.isEven(24) = true
%nMyInteger.isOdd(24) = false
%nMyInteger.isPrime(24) = false
Enter a positive integer to test static isXXX(int) methods or to move on to next part of program:Enter a positive integer to test static isXXX(MyInteger) methods or to move on to next part of program:MyInteger obj1 = new MyInteger(1);
obj1.getValue() = 1
MyInteger.isEven(obj1) = false
MyInteger.isOdd(obj1) = true
MyInteger.isPrime(obj1) = false
Enter a positive integer to test static isXXX(MyInteger) methods or to move on to next part of program:MyInteger obj1 = new MyInteger(2);
obj1.getValue() = 2
MyInteger.isEven(obj1) = true
MyInteger.isOdd(obj1) = false
MyInteger.isPrime(obj1) = true
Enter a positive integer to test static isXXX(MyInteger) methods or to move on to next part of program:MyInteger obj1 = new MyInteger(5);
obj1.getValue() = 5
MyInteger.isEven(obj1) = false
MyInteger.isOdd(obj1) = true
MyInteger.isPrime(obj1) = true
Enter a positive integer to test static isXXX(MyInteger) methods or to move on to next part of program:MyInteger obj1 = new MyInteger(22);
obj1.getValue() = 22
MyInteger.isEven(obj1) = true
MyInteger.isOdd(obj1) = false
MyInteger.isPrime(obj1) = false
Enter a positive integer to test static isXXX(MyInteger) methods or to move on to next part of program:MyInteger obj1 = new MyInteger(19);
obj1.getValue() = 19
MyInteger.isEven(obj1) = false
MyInteger.isOdd(obj1) = true
MyInteger.isPrime(obj1) = true
Enter a positive integer to test static isXXX(MyInteger) methods or to move on to next part of program:Enter a the first of two positive integers to create obj2 and test obj2.equals(int) or to move on to next part of program:MyInteger obj2 = new MyInteger(22);
obj2.getValue() = 22
Enter a the second of two positive integers to test obj2.equals(int):obj2.equals(22) = true
Enter a the first of two positive integers to create obj2 and test obj2.equals(int) or to move on to next part of program:MyInteger obj2 = new MyInteger(33);
obj2.getValue() = 33
Enter a the second of two positive integers to test obj2.equals(int):obj2.equals(33) = true
Enter a the first of two positive integers to create obj2 and test obj2.equals(int) or to move on to next part of program:MyInteger obj2 = new MyInteger(33);
obj2.getValue() = 33
Enter a the second of two positive integers to test obj2.equals(int):obj2.equals(34) = false
Enter a the first of two positive integers to create obj2 and test obj2.equals(int) or to move on to next part of program:Enter a the first of two positive integers to create obj2 and test obj2.equals(MyInteger obj3) or to move on to next part of program:MyInteger obj2 = new MyInteger(11);
obj2.getValue() = 11
Enter a the second of two positive integers to create obj3 and test obj2.equals(MyInteger obj3):MyInteger obj3 = new MyInteger(11);
obj3.getValue() = 11
obj2.equals(obj3) = true
Enter a the first of two positive integers to create obj2 and test obj2.equals(MyInteger obj3) or to move on to next part of program:MyInteger obj2 = new MyInteger(1);
obj2.getValue() = 1
Enter a the second of two positive integers to create obj3 and test obj2.equals(MyInteger obj3):MyInteger obj3 = new MyInteger(1);
obj3.getValue() = 1
obj2.equals(obj3) = true
Enter a the first of two positive integers to create obj2 and test obj2.equals(MyInteger obj3) or to move on to next part of program:MyInteger obj2 = new MyInteger(1);
obj2.getValue() = 1
Enter a the second of two positive integers to create obj3 and test obj2.equals(MyInteger obj3):MyInteger obj3 = new MyInteger(2);
obj3.getValue() = 2
obj2.equals(obj3) = false
Enter a the first of two positive integers to create obj2 and test obj2.equals(MyInteger obj3) or to move on to next part of program:Enter a positive integer that will be placed into a char[] array to demonstrate the MyInteger.parseInt(char[]):MyInteger obj4 = new MyInteger(MyInteger.parseInt(char []);
obj4.getValue() = 125
obj4.isEven() = false
obj4.isOdd() = true
obj4.isPrime() = false
Enter a positive integer that will be placed into a char[] array to demonstrate the MyInteger.parseInt(char[]):MyInteger obj4 = new MyInteger(MyInteger.parseInt(char []);
obj4.getValue() = 256
obj4.isEven() = true
obj4.isOdd() = false
obj4.isPrime() = false
Enter a positive integer that will be placed into a char[] array to demonstrate the MyInteger.parseInt(char[]):Enter a positive integer that will be placed into a String to demonstrate the MyInteger.parseInt(String):MyInteger obj5 = new MyInteger(MyInteger.parseInt(String);
obj5.getValue() = 333
obj5.isEven() = false
obj5.isOdd() = true
obj5.isPrime() = false
Enter a positive integer that will be placed into a String to demonstrate the MyInteger.parseInt(String):MyInteger obj5 = new MyInteger(MyInteger.parseInt(String);
obj5.getValue() = 444
obj5.isEven() = true
obj5.isOdd() = false
obj5.isPrime() = false
Enter a positive integer that will be placed into a String to demonstrate the MyInteger.parseInt(String):MyInteger obj5 = new MyInteger(MyInteger.parseInt(String);
obj5.getValue() = 987
obj5.isEven() = false
obj5.isOdd() = true
obj5.isPrime() = false
Enter a positive integer that will be placed into a String to demonstrate the MyInteger.parseInt(String):")